FROM python:3.10

# 设置工作目录：后续命令将在这个目录下执行
WORKDIR /app

# 复制文件：将当前目录下的 requirements.txt 复制到容器的 /app 目录
COPY requirements.txt .

# 安装依赖：运行 pip 命令安装所需的 Python 包
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码：将当前目录下的所有文件复制到容器的 /app 目录
COPY . .

# streamlit hello创建一个演示页面，映射80端口以便网页访问
CMD ["streamlit","hello", "--server.port","80"]